### ISSUE TITLE
Optimize GatherEntityIdsToDelete

### ISSUE THREAD

**Issue by vadash** [Queuete/ExileApi#173] opened 2021-05-19 13:18 UTC
DPA shows it took over 6 GB heap 
![image](https://user-images.githubusercontent.com/1397582/118819191-c5b16880-b8bd-11eb-9eb1-b09a7a090ea1.png)

**Comment by Queuete** [comment] 2021-05-19 20:06
Please add a bit more of information for reproduction. I am neither seeing huge memory consumption nor do I see this function in the DPA (in Visual studio). The heap memory useage is increasing slightly over time (~16MB at start ~18MB after 30 min), which is mostly attributed to CoroutineDetails. 
The Code seems to be some form of compiler optimized code? its certainly not the source code of this function.

**Comment by Queuete** [comment] 2021-05-26 07:32
Was this a "one-time-thing"?
I usually see the Memory.Read(...ComponentOffsets) issues in there aswell, but nothing related to GatherEntitiyIdsToDelete.

Without any further comments I will close this issue soon.

**Closed** 2021-05-26 17:27 UTC
